### ISSUE TITLE
basic search bar functionality

### ISSUE THREAD

**Issue by reedv** [alloyteams/alloy#12]
The Projects collection does not having anything like a helpWanted field (just b/c I don't know if that is the route we want to go, implementation wise),  but for a start you we could have a search bar that just searches for projects in the Projects collection based on a keywords array field (and maybe even the project's bio field as well as simple auto-complete/correct for words).
Use case:
1. In the header menu, type in "surfing"
2. You get taken to a search-page.html page, or something, showing all projects with "surf" or "surfing" as keyword or in bio.
3. each project has a clickable button that links to their project profile.

**Comment by neilnthings** [comment]
Basic search functionality working.  Users are able to search for projects by skills.
