### ISSUE TITLE
Implement skill graph datastructure <DB>

### ISSUE THREAD

**Issue by reedv** [alloyteams/alloy#9]
If you look [here](https://github.com/radgrad/radgrad/blob/master/app/imports/api/base/BaseCollection.js), you can see an example of using a class to hold a collection, acting on that collection (say, as a graph), and exporting a single instance of that class that all other files can import to access. 

This may be an implementation option that you may be interested in.
You may want to break this issues into slightly smaller ones.

**Comment by byerst** [comment]
We have elected to go with Reed's implementation of the graph in mongoDB and will begin developing an interface for interacting with the data
